// Generated by lsc from domain.ts

datatype Lap = Lap(timestamp: int, duration: int, section: string, selected: bool, expectedDuration: int, tags: seq<string>)

datatype TemplateEntry = TemplateEntry(section: string, expectedDuration: int, tags: seq<string>)

datatype Model = Model(currentTime: int, lastLapTime: int, laps: seq<Lap>, template: seq<TemplateEntry>, originalTemplate: seq<TemplateEntry>, activeSection: int)

datatype Action = SetTime(ms: int) | CreateLap | LabelLap(idx: int, name: string) | SelectLap(idx: int) | DeleteLap(idx: int) | AdjustDuration(idx: int, duration: int) | MoveUp(idx: int) | MoveDown(idx: int) | AddTag(idx: int, tag: string) | RemoveTag(idx: int, tag: string) | SetTemplate(labels: seq<TemplateEntry>) | ConsumeTemplate | SetActiveSection(idx: int) | ApplyActiveSection | AdvanceTemplateAfter(idx: int) | ImportLaps(laps: seq<Lap>) | Reset

datatype History = History(past: seq<Model>, present: Model, future: seq<Model>)

function addTagToSeq(tags: seq<string>, tag: string): seq<string>
{
  if (tag in tags) then
    tags
  else
    (tags + [tag])
}

lemma addTagToSeq_ensures(tags: seq<string>, tag: string)
  ensures (tag in addTagToSeq(tags, tag))
{
}

function removeTagFromSeq(tags: seq<string>, tag: string): seq<string>
  decreases |tags|
{
  if (|tags| == 0) then
    []
  else
    var rest := removeTagFromSeq(tags[1..], tag);
    if (tags[0] == tag) then
      rest
    else
      ([tags[0]] + rest)
}

lemma removeTagFromSeq_ensures(tags: seq<string>, tag: string)
  ensures !((tag in removeTagFromSeq(tags, tag)))
{
}

function lapValid(l: Lap): bool
{
  (((l.timestamp >= 0) && (l.duration >= 0)) && (l.expectedDuration >= -1))
}

function lapsValid(laps: seq<Lap>): bool
{
  Std.Collections.Seq.All(laps, lapValid)
}

function clampLap(lap: Lap): Lap
{
  Lap((if (lap.timestamp >= 0) then lap.timestamp else 0), (if (lap.duration >= 0) then lap.duration else 0), lap.section, lap.selected, (if (lap.expectedDuration >= -1) then lap.expectedDuration else -1), lap.tags)
}

lemma clampLap_ensures(lap: Lap)
  ensures (clampLap(lap).timestamp >= 0)
  ensures (clampLap(lap).duration >= 0)
  ensures (clampLap(lap).expectedDuration >= -1)
{
}

function clampLaps(laps: seq<Lap>): seq<Lap>
  decreases |laps|
{
  if (|laps| == 0) then
    []
  else
    ([clampLap(laps[0])] + clampLaps(laps[1..]))
}

lemma clampLaps_ensures(laps: seq<Lap>)
  ensures (|clampLaps(laps)| == |laps|)
  ensures lapsValid(clampLaps(laps))
{
}

function templateEntryToLap(entry: TemplateEntry): Lap
{
  Lap(0, (if (entry.expectedDuration >= 0) then entry.expectedDuration else 0), entry.section, true, -1, entry.tags)
}

lemma templateEntryToLap_ensures(entry: TemplateEntry)
  ensures (templateEntryToLap(entry).timestamp >= 0)
  ensures (templateEntryToLap(entry).duration >= 0)
  ensures (templateEntryToLap(entry).expectedDuration == -1)
{
}

function templateToLaps(template: seq<TemplateEntry>): seq<Lap>
  decreases |template|
{
  if (|template| == 0) then
    []
  else
    ([templateEntryToLap(template[0])] + templateToLaps(template[1..]))
}

lemma templateToLaps_ensures(template: seq<TemplateEntry>)
  ensures (|templateToLaps(template)| == |template|)
  ensures lapsValid(templateToLaps(template))
{
}

function inv(m: Model): bool
{
  ((((((m.currentTime >= 0) && (m.lastLapTime >= 0)) && (m.lastLapTime <= m.currentTime)) && lapsValid(m.laps)) && (m.activeSection >= -1)) && ((m.activeSection < 0) || (m.activeSection < |m.originalTemplate|)))
}

function init(): Model
{
  Model(0, 0, [], [], [], -1)
}

lemma init_ensures()
  ensures inv(init())
{
}

function setAt<T>(s: seq<T>, i: int, x: T): seq<T>
  requires (i >= 0)
  requires (i < |s|)
{
  ((s[0..i] + [x]) + s[(i + 1)..])
}

lemma setAt_ensures<T>(s: seq<T>, i: int, x: T)
  requires (i >= 0)
  requires (i < |s|)
  ensures (|setAt(s, i, x)| == |s|)
{
}

function removeAt<T>(s: seq<T>, i: int): seq<T>
  requires (i >= 0)
  requires (i < |s|)
{
  (s[0..i] + s[(i + 1)..])
}

lemma removeAt_ensures<T>(s: seq<T>, i: int)
  requires (i >= 0)
  requires (i < |s|)
  ensures (|removeAt(s, i)| == (|s| - 1))
{
}

function applySetTime(m: Model, ms: int): Model
  requires inv(m)
{
  if (ms >= m.currentTime) then
    m.(currentTime := ms)
  else
    m
}

lemma applySetTime_ensures(m: Model, ms: int)
  requires inv(m)
  ensures inv(applySetTime(m, ms))
{
}

function applyCreateLap(m: Model): Model
  requires inv(m)
{
  var duration := (m.currentTime - m.lastLapTime);
  var newLap := Lap(m.currentTime, duration, "", false, -1, []);
  m.(lastLapTime := m.currentTime, laps := (m.laps + [newLap]))
}

lemma applyCreateLap_ensures(m: Model)
  requires inv(m)
  ensures inv(applyCreateLap(m))
{
}

function applyLabelLap(m: Model, idx: int, name: string): Model
  requires inv(m)
{
  if ((idx < 0) || (idx >= |m.laps|)) then
    m
  else
    var updated := m.laps[idx].(section := name);
    m.(laps := setAt(m.laps, idx, updated))
}

lemma applyLabelLap_ensures(m: Model, idx: int, name: string)
  requires inv(m)
  ensures inv(applyLabelLap(m, idx, name))
{
}

function applySelectLap(m: Model, idx: int): Model
  requires inv(m)
{
  if ((idx < 0) || (idx >= |m.laps|)) then
    m
  else
    var updated := m.laps[idx].(selected := !(m.laps[idx].selected));
    m.(laps := setAt(m.laps, idx, updated))
}

lemma applySelectLap_ensures(m: Model, idx: int)
  requires inv(m)
  ensures inv(applySelectLap(m, idx))
{
}

function applyDeleteLap(m: Model, idx: int): Model
  requires inv(m)
{
  if ((idx < 0) || (idx >= |m.laps|)) then
    m
  else
    m.(laps := removeAt(m.laps, idx))
}

lemma applyDeleteLap_ensures(m: Model, idx: int)
  requires inv(m)
  ensures inv(applyDeleteLap(m, idx))
{
}

function applyAdjustDuration(m: Model, idx: int, duration: int): Model
  requires inv(m)
{
  if ((idx < 0) || (idx >= |m.laps|)) then
    m
  else
    if (duration < 0) then
      m
    else
      var updated := m.laps[idx].(duration := duration);
      m.(laps := setAt(m.laps, idx, updated))
}

lemma applyAdjustDuration_ensures(m: Model, idx: int, duration: int)
  requires inv(m)
  ensures inv(applyAdjustDuration(m, idx, duration))
{
}

function applyMoveUp(m: Model, idx: int): Model
  requires inv(m)
{
  if ((idx < 1) || (idx >= |m.laps|)) then
    m
  else
    var a := m.laps[(idx - 1)];
    var b := m.laps[idx];
    var newLaps := setAt(setAt(m.laps, (idx - 1), b), idx, a);
    m.(laps := newLaps)
}

lemma applyMoveUp_ensures(m: Model, idx: int)
  requires inv(m)
  ensures inv(applyMoveUp(m, idx))
{
}

function applyMoveDown(m: Model, idx: int): Model
  requires inv(m)
{
  if ((idx < 0) || (idx >= (|m.laps| - 1))) then
    m
  else
    var a := m.laps[idx];
    var b := m.laps[(idx + 1)];
    var newLaps := setAt(setAt(m.laps, idx, b), (idx + 1), a);
    m.(laps := newLaps)
}

lemma applyMoveDown_ensures(m: Model, idx: int)
  requires inv(m)
  ensures inv(applyMoveDown(m, idx))
{
}

function applyAddTag(m: Model, idx: int, tag: string): Model
  requires inv(m)
{
  if ((idx < 0) || (idx >= |m.laps|)) then
    m
  else
    var newTags := addTagToSeq(m.laps[idx].tags, tag);
    var updated := m.laps[idx].(tags := newTags);
    m.(laps := setAt(m.laps, idx, updated))
}

lemma applyAddTag_ensures(m: Model, idx: int, tag: string)
  requires inv(m)
  ensures inv(applyAddTag(m, idx, tag))
{
}

function applyRemoveTag(m: Model, idx: int, tag: string): Model
  requires inv(m)
{
  if ((idx < 0) || (idx >= |m.laps|)) then
    m
  else
    var newTags := removeTagFromSeq(m.laps[idx].tags, tag);
    var updated := m.laps[idx].(tags := newTags);
    m.(laps := setAt(m.laps, idx, updated))
}

lemma applyRemoveTag_ensures(m: Model, idx: int, tag: string)
  requires inv(m)
  ensures inv(applyRemoveTag(m, idx, tag))
{
}

function applySetTemplate(m: Model, labels: seq<TemplateEntry>): Model
  requires inv(m)
{
  m.(template := labels, originalTemplate := labels, activeSection := -1)
}

lemma applySetTemplate_ensures(m: Model, labels: seq<TemplateEntry>)
  requires inv(m)
  ensures inv(applySetTemplate(m, labels))
{
}

function applyConsumeTemplate(m: Model): Model
  requires inv(m)
{
  if (|m.template| == 0) then
    m
  else
    if (|m.laps| == 0) then
      m
    else
      var idx := (|m.laps| - 1);
      var entry := m.template[0];
      var expectedDur := (if (entry.expectedDuration >= 0) then entry.expectedDuration else -1);
      var updated := m.laps[idx].(section := entry.section, selected := true, expectedDuration := expectedDur, tags := entry.tags);
      m.(laps := setAt(m.laps, idx, updated), template := m.template[1..])
}

lemma applyConsumeTemplate_ensures(m: Model)
  requires inv(m)
  ensures inv(applyConsumeTemplate(m))
{
}

function applySetActiveSection(m: Model, idx: int): Model
  requires inv(m)
{
  if (idx < -1) then
    m
  else
    if ((idx >= 0) && (idx >= |m.originalTemplate|)) then
      m
    else
      m.(activeSection := idx)
}

lemma applySetActiveSection_ensures(m: Model, idx: int)
  requires inv(m)
  ensures inv(applySetActiveSection(m, idx))
{
}

function applyApplyActiveSection(m: Model): Model
  requires inv(m)
{
  if (m.activeSection < 0) then
    m
  else
    if (m.activeSection >= |m.originalTemplate|) then
      m
    else
      if (|m.laps| == 0) then
        m
      else
        var lapIdx := (|m.laps| - 1);
        var entry := m.originalTemplate[m.activeSection];
        var expectedDur := (if (entry.expectedDuration >= 0) then entry.expectedDuration else -1);
        var updated := m.laps[lapIdx].(section := entry.section, selected := true, expectedDuration := expectedDur, tags := entry.tags);
        m.(laps := setAt(m.laps, lapIdx, updated))
}

lemma applyApplyActiveSection_ensures(m: Model)
  requires inv(m)
  ensures inv(applyApplyActiveSection(m))
{
}

function applyAdvanceTemplateAfter(m: Model, idx: int): Model
  requires inv(m)
{
  if ((idx < 0) || (idx >= |m.originalTemplate|)) then
    m
  else
    var newTemplate := m.originalTemplate[(idx + 1)..];
    m.(template := newTemplate, activeSection := -1)
}

lemma applyAdvanceTemplateAfter_ensures(m: Model, idx: int)
  requires inv(m)
  ensures inv(applyAdvanceTemplateAfter(m, idx))
{
}

function applyImportLaps(m: Model, laps: seq<Lap>): Model
  requires inv(m)
{
  var validLaps := clampLaps(laps);
  m.(laps := (m.laps + validLaps))
}

lemma applyImportLaps_ensures(m: Model, laps: seq<Lap>)
  requires inv(m)
  ensures inv(applyImportLaps(m, laps))
{
}

function applyReset(m: Model): Model
  requires inv(m)
{
  if (|m.originalTemplate| > 0) then
    Model(m.currentTime, m.currentTime, templateToLaps(m.originalTemplate), [], [], -1)
  else
    Model(m.currentTime, m.currentTime, [], [], [], -1)
}

lemma applyReset_ensures(m: Model)
  requires inv(m)
  ensures inv(applyReset(m))
{
}

function apply(m: Model, a: Action): Model
  requires inv(m)
{
  match a {
    case SetTime(i_a_ms) =>
      applySetTime(m, i_a_ms)
    case CreateLap =>
      applyCreateLap(m)
    case LabelLap(i_a_idx, i_a_name) =>
      applyLabelLap(m, i_a_idx, i_a_name)
    case SelectLap(i_a_idx) =>
      applySelectLap(m, i_a_idx)
    case DeleteLap(i_a_idx) =>
      applyDeleteLap(m, i_a_idx)
    case AdjustDuration(i_a_idx, i_a_duration) =>
      applyAdjustDuration(m, i_a_idx, i_a_duration)
    case MoveUp(i_a_idx) =>
      applyMoveUp(m, i_a_idx)
    case MoveDown(i_a_idx) =>
      applyMoveDown(m, i_a_idx)
    case AddTag(i_a_idx, i_a_tag) =>
      applyAddTag(m, i_a_idx, i_a_tag)
    case RemoveTag(i_a_idx, i_a_tag) =>
      applyRemoveTag(m, i_a_idx, i_a_tag)
    case SetTemplate(i_a_labels) =>
      applySetTemplate(m, i_a_labels)
    case ConsumeTemplate =>
      applyConsumeTemplate(m)
    case SetActiveSection(i_a_idx) =>
      applySetActiveSection(m, i_a_idx)
    case ApplyActiveSection =>
      applyApplyActiveSection(m)
    case AdvanceTemplateAfter(i_a_idx) =>
      applyAdvanceTemplateAfter(m, i_a_idx)
    case ImportLaps(i_a_laps) =>
      applyImportLaps(m, i_a_laps)
    case Reset =>
      applyReset(m)
  }
}

lemma apply_ensures(m: Model, a: Action)
  requires inv(m)
  ensures inv(apply(m, a))
{
}

function sumFrom(s: seq<int>, i: nat): int
  requires (i <= |s|)
  decreases (|s| - i)
{
  if (i >= |s|) then
    0
  else
    (s[i] + sumFrom(s, (i + 1)))
}

function selectedDurations(laps: seq<Lap>): seq<int>
  decreases |laps|
{
  if (|laps| == 0) then
    []
  else
    var rest := selectedDurations(laps[1..]);
    if laps[0].selected then
      ([laps[0].duration] + rest)
    else
      rest
}

function selectedTotal(laps: seq<Lap>): int
{
  sumFrom(selectedDurations(laps), 0)
}

function selectedCount(laps: seq<Lap>): int
{
  |selectedDurations(laps)|
}

lemma selectedCount_ensures(laps: seq<Lap>)
  ensures (selectedCount(laps) >= 0)
{
}

function lapHasTag(lap: Lap, tag: string): bool
{
  (tag in lap.tags)
}

function sumByTag(laps: seq<Lap>, tag: string): int
  decreases |laps|
{
  if (|laps| == 0) then
    0
  else
    var rest := sumByTag(laps[1..], tag);
    if (laps[0].selected && lapHasTag(laps[0], tag)) then
      (laps[0].duration + rest)
    else
      rest
}

function countByTag(laps: seq<Lap>, tag: string): int
  decreases |laps|
{
  if (|laps| == 0) then
    0
  else
    var rest := countByTag(laps[1..], tag);
    if (laps[0].selected && lapHasTag(laps[0], tag)) then
      (1 + rest)
    else
      rest
}

lemma countByTag_ensures(laps: seq<Lap>, tag: string)
  ensures (countByTag(laps, tag) >= 0)
{
}

function addUniqueTags(seen: seq<string>, tags: seq<string>): seq<string>
  decreases |tags|
{
  if (|tags| == 0) then
    seen
  else
    if (tags[0] in seen) then
      addUniqueTags(seen, tags[1..])
    else
      addUniqueTags((seen + [tags[0]]), tags[1..])
}

function collectAllTagsHelper(laps: seq<Lap>, seen: seq<string>): seq<string>
  decreases |laps|
{
  if (|laps| == 0) then
    seen
  else
    var newTags := (if laps[0].selected then laps[0].tags else []);
    var updatedSeen := addUniqueTags(seen, newTags);
    collectAllTagsHelper(laps[1..], updatedSeen)
}

function collectAllTags(laps: seq<Lap>): seq<string>
{
  collectAllTagsHelper(laps, [])
}

function sumBySection(laps: seq<Lap>, section: string): int
  decreases |laps|
{
  if (|laps| == 0) then
    0
  else
    var rest := sumBySection(laps[1..], section);
    if (laps[0].selected && (laps[0].section == section)) then
      (laps[0].duration + rest)
    else
      rest
}

function countBySection(laps: seq<Lap>, section: string): int
  decreases |laps|
{
  if (|laps| == 0) then
    0
  else
    var rest := countBySection(laps[1..], section);
    if (laps[0].selected && (laps[0].section == section)) then
      (1 + rest)
    else
      rest
}

lemma countBySection_ensures(laps: seq<Lap>, section: string)
  ensures (countBySection(laps, section) >= 0)
{
}

function minBySectionHelper(laps: seq<Lap>, section: string, currentMin: int): int
  requires lapsValid(laps)
  requires (currentMin >= -1)
  decreases |laps|
{
  if (|laps| == 0) then
    currentMin
  else
    if (laps[0].selected && (laps[0].section == section)) then
      var newMin := (if (currentMin == -1) then laps[0].duration else (if (laps[0].duration < currentMin) then laps[0].duration else currentMin));
      minBySectionHelper(laps[1..], section, newMin)
    else
      minBySectionHelper(laps[1..], section, currentMin)
}

lemma minBySectionHelper_ensures(laps: seq<Lap>, section: string, currentMin: int)
  requires lapsValid(laps)
  requires (currentMin >= -1)
  ensures (minBySectionHelper(laps, section, currentMin) >= -1)
{
}

function minBySection(laps: seq<Lap>, section: string): int
  requires lapsValid(laps)
{
  minBySectionHelper(laps, section, -1)
}

lemma minBySection_ensures(laps: seq<Lap>, section: string)
  requires lapsValid(laps)
  ensures (minBySection(laps, section) >= -1)
{
}

function maxBySectionHelper(laps: seq<Lap>, section: string, currentMax: int): int
  requires lapsValid(laps)
  requires (currentMax >= -1)
  decreases |laps|
{
  if (|laps| == 0) then
    currentMax
  else
    if (laps[0].selected && (laps[0].section == section)) then
      var newMax := (if (laps[0].duration > currentMax) then laps[0].duration else currentMax);
      maxBySectionHelper(laps[1..], section, newMax)
    else
      maxBySectionHelper(laps[1..], section, currentMax)
}

lemma maxBySectionHelper_ensures(laps: seq<Lap>, section: string, currentMax: int)
  requires lapsValid(laps)
  requires (currentMax >= -1)
  ensures (maxBySectionHelper(laps, section, currentMax) >= -1)
{
}

function maxBySection(laps: seq<Lap>, section: string): int
  requires lapsValid(laps)
{
  maxBySectionHelper(laps, section, -1)
}

lemma maxBySection_ensures(laps: seq<Lap>, section: string)
  requires lapsValid(laps)
  ensures (maxBySection(laps, section) >= -1)
{
}

function collectAllSectionsHelper(laps: seq<Lap>, seen: seq<string>): seq<string>
  decreases |laps|
{
  if (|laps| == 0) then
    seen
  else
    if (laps[0].selected && (laps[0].section != "")) then
      var section := laps[0].section;
      var updatedSeen := (if (section in seen) then seen else (seen + [section]));
      collectAllSectionsHelper(laps[1..], updatedSeen)
    else
      collectAllSectionsHelper(laps[1..], seen)
}

function collectAllSections(laps: seq<Lap>): seq<string>
{
  collectAllSectionsHelper(laps, [])
}

function runningTotalsHelper(laps: seq<Lap>, acc: int): seq<int>
  decreases |laps|
{
  if (|laps| == 0) then
    []
  else
    var newAcc := (if laps[0].selected then (acc + laps[0].duration) else acc);
    ([acc] + runningTotalsHelper(laps[1..], newAcc))
}

lemma runningTotalsHelper_ensures(laps: seq<Lap>, acc: int)
  ensures (|runningTotalsHelper(laps, acc)| == |laps|)
{
}

function runningTotals(laps: seq<Lap>): seq<int>
{
  runningTotalsHelper(laps, 0)
}

lemma runningTotals_ensures(laps: seq<Lap>)
  ensures (|runningTotals(laps)| == |laps|)
{
}

function histInv(h: History): bool
{
  ((Std.Collections.Seq.All(h.past, inv) && inv(h.present)) && Std.Collections.Seq.All(h.future, inv))
}

function initHistory(): History
{
  History([], init(), [])
}

lemma initHistory_ensures()
  ensures histInv(initHistory())
{
}

function doAction(h: History, a: Action): History
  requires histInv(h)
{
  History((h.past + [h.present]), apply(h.present, a), [])
}

lemma doAction_ensures(h: History, a: Action)
  requires histInv(h)
  ensures histInv(doAction(h, a))
{
}

function preview(h: History, a: Action): History
  requires histInv(h)
{
  History(h.past, apply(h.present, a), h.future)
}

lemma preview_ensures(h: History, a: Action)
  requires histInv(h)
  ensures histInv(preview(h, a))
{
}

function commitFrom(h: History, baseline: Model): History
  requires histInv(h)
  requires inv(baseline)
{
  History((h.past + [baseline]), h.present, [])
}

lemma commitFrom_ensures(h: History, baseline: Model)
  requires histInv(h)
  requires inv(baseline)
  ensures histInv(commitFrom(h, baseline))
{
}

function undo(h: History): History
  requires histInv(h)
{
  if (|h.past| == 0) then
    h
  else
    var i := (|h.past| - 1);
    History(h.past[0..i], h.past[i], ([h.present] + h.future))
}

lemma undo_ensures(h: History)
  requires histInv(h)
  ensures histInv(undo(h))
{
}

function redo(h: History): History
  requires histInv(h)
{
  if (|h.future| == 0) then
    h
  else
    History((h.past + [h.present]), h.future[0], h.future[1..])
}

lemma redo_ensures(h: History)
  requires histInv(h)
  ensures histInv(redo(h))
{
}
